import { getCategoryByIdAPI } from "../api/category/get-category-by-id.api.js";
import { getAllCategoryTreeAPI } from "../api/category/get-category-tree.api.js";
import express from "express";
import { authenticateUser } from "../middleware/auth.middleware.js";
import { getCustomerProfileAPI } from "../api/customer/get-profile.api.js";
import { getAllAvailableProductsAPI } from "../api/product/get-all-available-product.js";
import { createOrderAPI } from "../api/order/create-order.api.js";
import { getProductByCategoryIdAPI } from "../api/product/get-product-by-category.api.js";
import { getAllCustomerProductOrders } from "../api/productOrder/get-all-customer-productorders.js";
import { rejectProductAPI } from "../api/customer/reject-product.api.js";
import { acceptProductAPI } from "../api/customer/accept-product.api.js";
import { getCartAPI } from "../api/cart/get-cart.api.js";
import { createCartAPI } from "../api/cart/create-cart.api.js";
import { updateCartAPI } from "../api/cart/update-cart.api.js";
import { deleteCartAPI } from "../api/cart/delete-cart.api.js";

const router = express.Router();
router.get("/category/:id", getCategoryByIdAPI);
router.get("/category", getAllCategoryTreeAPI);
router.get("/product", getAllAvailableProductsAPI);
router.get("/product/:categoryId", getProductByCategoryIdAPI);
router.get("/profile", authenticateUser, getCustomerProfileAPI);
router.post("/checkout", authenticateUser, createOrderAPI);
router.get("/order", authenticateUser, getAllCustomerProductOrders);
router.patch("/order/reject/:id", authenticateUser, rejectProductAPI);
router.patch("/order/accept/:id", authenticateUser, acceptProductAPI);
router.get("/cart", authenticateUser, getCartAPI);
router.post("/cart", authenticateUser, createCartAPI);
router.put("/cart", authenticateUser, updateCartAPI);
router.delete("/cart", authenticateUser, deleteCartAPI);
export const customerRouter = router;
